import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { test } from "node:test";

const root = process.cwd();
const legalFooterPattern = /© 2026 Boaz Alhadeff[\s\S]*Apache-2\.0[\s\S]*NOTICE/;
const generatedMarker = /Generated by scripts\/generate-public-site\.js/;
const projectHtmlPages = [
  "index.html",
  "features-qa.html",
  "verify-remote.html",
  "manifesto/index.html",
  "media-kit/index.html",
  "docs/index.html",
  "docs/alpha-2/index.html",
  "docs/how-to-use/index.html",
  "docs/cli/index.html",
  "docs/headless-publishing/index.html",
  "docs/publish-surge/index.html",
  "docs/publishing/index.html",
  "docs/snaillift/index.html",
  "docs/snaillift-surge/index.html",
  "docs/snaillift-security/index.html",
  "docs/comments/index.html",
  "docs/signature-badges/index.html",
  "docs/shellnames/index.html",
  "docs/shellnames-protocol/index.html",
  "docs/shellnames-security/index.html",
  "docs/concept/index.html",
  "docs/architecture/index.html",
  "docs/core-foundation/index.html",
  "docs/plugin-system/index.html",
  "docs/plugin-migrations/index.html",
  "docs/theme-system/index.html",
  "docs/theme-manifests/index.html",
  "docs/route-assets/index.html",
  "docs/permissions/index.html",
  "docs/extension-security/index.html",
  "docs/compatibility/index.html",
  "docs/protocol/index.html",
  "docs/workspace-vault/index.html",
  "docs/security/index.html",
  "docs/migrations/index.html",
  "docs/psep/index.html",
  "docs/legal/index.html",
];

function read(path) {
  return readFileSync(join(root, path), "utf8");
}

test("public landing page is separate from the browser admin", () => {
  const html = read("index.html");

  assert.match(html, /PostSnail Alpha 2/);
  assert.match(html, /id="landing-search"/);
  assert.match(html, /data-forest-url="https:\/\/forest\.postsnail\.org\/"/);
  assert.match(html, /googletagmanager\.com\/gtag\/js\?id=G-XVB04MP13V/);
  assert.doesNotMatch(html, /id="app" class="app-shell"/);
  assert.doesNotMatch(html, /src="\.\/app\.js"/);
});

test("admin shell is reachable from /admin/", () => {
  const html = read("admin/index.html");

  assert.match(html, /PostSnail - Static Microblog Admin/);
  assert.match(html, /<main id="app" class="app-shell"/);
  assert.match(html, /href="\.\.\/styles\.css"/);
  assert.match(html, /src="\.\.\/app\.js"/);
  assert.match(html, /googletagmanager\.com\/gtag\/js\?id=G-XVB04MP13V/);
  assert.match(html, legalFooterPattern);
});

test("public pages are generated from the shared PostSnail layout", () => {
  assert.ok(existsSync(join(root, "scripts/generate-public-site.js")));
  execFileSync(process.execPath, ["scripts/generate-public-site.js"], {
    cwd: root,
    stdio: "pipe",
  });

  for (const path of projectHtmlPages) {
    const html = read(path);
    assert.match(html, generatedMarker, path);
    assert.match(html, /googletagmanager\.com\/gtag\/js\?id=G-XVB04MP13V/, path);
    assert.match(html, /class="site-footer"/, path);
    assert.match(html, legalFooterPattern, path);
    assert.match(html, /href="\/docs\/legal\/"/, path);
    assert.match(html, /href="\/LICENSE"/, path);
    assert.match(html, /href="\/NOTICE"/, path);
    assert.match(html, /href="\/THIRD_PARTY_NOTICES\.md"/, path);
    if (path === "docs/index.html") {
      assert.doesNotMatch(html, /href="\/docs\/portable-bundle\/"/, path);
    }
    if (path === "docs/cli/index.html") {
      assert.match(html, /trusted local automation interface/, path);
      assert.doesNotMatch(html, /guided terminal TUI|postsnail menu|Command Center/, path);
    }
  }
});

test("admin app uses the PostSnail brand skin and compact legal footer", () => {
  const appJs = read("app.js");
  const css = read("styles.css");
  const headers = read("_headers");
  const submitSiteMoveSource = appJs.slice(
    appJs.indexOf("async function submitSiteMove()"),
    appJs.indexOf("async function generateSiteZip()"),
  );
  const contentEditorSource = appJs.slice(
    appJs.indexOf("function renderContentEditor()"),
    appJs.indexOf("function renderMarkdownToolbar()"),
  );

  assert.match(appJs, /renderShellGate/);
  assert.match(appJs, /Open Existing Shell/);
  assert.match(appJs, /Create New Shell/);
  assert.match(appJs, /This creates your private encrypted Shell\. No account\. No email\. No backend login\./);
  assert.match(appJs, /Launch your microblog/);
  assert.match(appJs, /Click here to read PostSnail's launch guide/);
  assert.match(appJs, /renderLaunchGuideDrawer/);
  assert.match(appJs, /data-action="open-launch-guide"/);
  assert.match(appJs, /aria-label="Read PostSnail launch guide"/);
  assert.match(appJs, /renderLaunchGuide/);
  assert.match(appJs, /Create Shell Identity/);
  assert.match(appJs, /Save Private Shell/);
  assert.match(appJs, /Name The Blog/);
  assert.match(appJs, /Create a Post/);
  assert.match(appJs, /Review And Export/);
  assert.match(appJs, /renderStatusRail/);
  assert.match(appJs, /Private Shell backup/);
  assert.match(appJs, /Public ZIP/);
  assert.match(appJs, /renderIdentityTabs/);
  assert.match(appJs, /identity-section/);
  assert.match(appJs, /data-section="signature"/);
  assert.match(appJs, /data-section="shellnames"/);
  assert.match(appJs, /data-section="domain"/);
  assert.match(appJs, /Signature key/);
  assert.match(appJs, /Forest aliases/);
  assert.match(appJs, /Need to unlock/);
  assert.match(appJs, /Unlock publisher key/);
  assert.match(appJs, /Check requirements and change domain/);
  assert.match(appJs, /Step 1: export and upload/);
  assert.match(appJs, /Step 2: verify and notify Forest/);
  assert.match(appJs, /renderGenerateTabs/);
  assert.match(appJs, /generate-section/);
  assert.match(appJs, /data-section="profile"/);
  assert.match(appJs, /data-section="export"/);
  assert.match(appJs, /data-section="publish"/);
  assert.match(appJs, /Profile/);
  assert.match(appJs, /Export ZIP/);
  assert.match(appJs, /Publish and Forest/);
  assert.match(appJs, /Continue writing/);
  assert.match(appJs, /adminNavigationItems/);
  assert.match(appJs, /enabledPluginNavigationItems/);
  assert.match(appJs, /Content/);
  assert.match(appJs, /data-action="content-section"/);
  assert.match(appJs, /data-section="posts"/);
  assert.match(appJs, /data-section="images"/);
  assert.match(appJs, /data-action="quick-post-status"/);
  assert.match(appJs, /data-action="delete-image"/);
  assert.match(appJs, /data-action="view-image"/);
  assert.match(appJs, /data-action="close-image-preview"/);
  assert.match(appJs, /renderImagePreviewDialog/);
  assert.match(appJs, /data-action="open-reading-preview"/);
  assert.match(appJs, /data-action="close-reading-preview"/);
  assert.match(appJs, /renderReadingPreviewDialog/);
  assert.match(appJs, /No-distraction reader preview/);
  assert.match(appJs, /renderMarkdownWithLocalAssets\(state\.form\.body/);
  assert.match(appJs, /localAssetPreviewSrc/);
  assert.match(appJs, /openAdminMenu/);
  assert.match(appJs, /data-admin-menu/);
  assert.match(appJs, /id === "image" \? "open-image-insert" : "md-helper"/);
  assert.match(appJs, /if \(action === "open-image-insert"\)/);
  assert.match(appJs, /renderImageInsertDialog/);
  assert.match(appJs, /data-action="insert-image-url"/);
  assert.match(appJs, /From gallery/);
  assert.match(appJs, /data-action="insert-gallery-image"/);
  assert.match(appJs, /markdown-image-upload/);
  assert.match(appJs, /insertUploadedImageAtCursor/);
  assert.match(appJs, /insertGalleryImageAtCursor/);
  assert.doesNotMatch(contentEditorSource, /id="image-upload"/);
  assert.doesNotMatch(contentEditorSource, /No images attached/);
  assert.match(appJs, /createPostSnailMarkdownEditor/);
  assert.match(appJs, /renderMarkdownEditorMount/);
  assert.match(appJs, /mountMarkdownEditor/);
  assert.match(appJs, /syncMarkdownEditorToForm/);
  assert.match(appJs, /state\.form\.body = state\.markdownEditor\.getMarkdown\(\)/);
  assert.match(appJs, /markdown-editor-mount/);
  assert.match(appJs, /vendor\/postsnail-editor\/editor\.bundle\.js/);
  assert.doesNotMatch(appJs, /renderMarkdownSourceEditor/);
  assert.doesNotMatch(appJs, /renderMarkdownSourceMarkup/);
  assert.doesNotMatch(appJs, /syncMarkdownSourceEditor/);
  assert.doesNotMatch(appJs, /contenteditable="true"/);
  assert.doesNotMatch(appJs, /markdown-source-editor/);
  assert.doesNotMatch(appJs, /md-heading/);
  assert.doesNotMatch(appJs, /markdown-style-layer/);
  assert.match(appJs, /\["h1", "H1"\]/);
  assert.match(appJs, /\["table", "Table"\]/);
  assert.doesNotMatch(appJs, /data-action="editor-mode"/);
  assert.doesNotMatch(appJs, /WYSIWYG/);
  assert.doesNotMatch(appJs, /markdownFromEditable/);
  assert.match(appJs, /Plugin compatibility notice/);
  assert.doesNotMatch(appJs, /\["write", "Write"\]/);
  assert.doesNotMatch(appJs, /\["library", "Library"\]/);
  assert.match(appJs, /Export ZIP/);
  assert.match(appJs, /Published in next ZIP/);
  assert.match(appJs, /Needs Shell export/);
  assert.match(appJs, /shell-trust-ribbon/);
  assert.match(appJs, /shell-trust-item/);
  assert.match(appJs, /open-shell-card/);
  assert.match(appJs, /create-shell-card/);
  assert.match(appJs, /recovery-shell-card/);
  assert.match(appJs, /Start a new writing notebook/);
  assert.match(appJs, /This creates a signature workspace, not an account/);
  assert.match(appJs, /shell-create-title/);
  assert.match(appJs, /data-profile-field="displayName"/);
  assert.match(appJs, /data-profile-field="siteUrl"/);
  assert.match(appJs, /shell-create-passphrase/);
  assert.match(appJs, /shell-create-confirm/);
  assert.match(appJs, /Unlock Local Shell/);
  assert.match(appJs, /Migrate Local Data/);
  assert.match(appJs, /Close Shell/);
  assert.match(appJs, /Old browser-local data is not locked yet/);
  assert.match(appJs, /A Shell is your private PostSnail workspace/);
  assert.match(appJs, /Your identity is a signature key, not a profile login/);
  assert.match(appJs, /No account\. No email\. No backend login\./);
  assert.match(appJs, /Your Shell stays private\. Your Website ZIP is public\./);
  assert.match(appJs, /renderAppFooter/);
  assert.match(appJs, /postsnail-icon\.png/);
  assert.match(appJs, /src="\.\.\/btc-wallet-qr\.svg"/);
  assert.match(appJs, /Export Shell/);
  assert.match(appJs, /ShellNames/);
  assert.match(appJs, /Extensions/);
  assert.match(appJs, /renderPagesAdmin/);
  assert.match(appJs, /PostSnail Pages/);
  assert.match(appJs, /postsnail-pages/);
  assert.match(appJs, /Pages CMS/);
  assert.match(appJs, /Pages CMS plugin panel/);
  assert.match(appJs, /data-action="new-pages-item"/);
  assert.match(appJs, /data-action="save-pages-item"/);
  assert.match(appJs, /data-action="delete-pages-item"/);
  assert.match(appJs, /data-action="pages-section"/);
  assert.match(appJs, /data-pages-field="title"/);
  assert.match(appJs, /data-pages-field="body"/);
  assert.match(appJs, /data-pages-seo-field="description"/);
  assert.match(appJs, /data-action="delete-unused-images"/);
  assert.match(appJs, /Delete unused/);
  assert.match(appJs, /renderCommentsAdmin/);
  assert.match(appJs, /PostSnail Comments/);
  assert.match(appJs, /postsnail-comments/);
  assert.match(appJs, /PostSnail Badges/);
  assert.match(appJs, /postsnail-badges/);
  assert.match(appJs, /data-action="save-badges-settings"/);
  assert.match(appJs, /data-action="delete-badge-claim"/);
  assert.match(appJs, /badge-claim-import/);
  assert.match(appJs, /Verified on import/);
  assert.match(appJs, /Badge collection/);
  assert.match(appJs, /data-action="save-comments-settings"/);
  assert.match(appJs, /data-action="verify-comment-packet"/);
  assert.match(appJs, /data-action="approve-comment-packet"/);
  assert.match(appJs, /data-action="reject-comment-packet"/);
  assert.match(appJs, /Approved comments/);
  assert.match(appJs, /Rejected comments/);
  assert.match(appJs, /Blocked author public keys/);
  assert.match(appJs, /renderExtensions/);
  assert.match(appJs, /Official bundled plugins/);
  assert.match(appJs, /postsnail-snaillift/);
  assert.match(appJs, /data-action="install-plugin"/);
  assert.match(appJs, /data-action="enable-plugin"/);
  assert.match(appJs, /data-action="disable-plugin"/);
  assert.match(appJs, /Review permissions/);
  assert.match(appJs, /deploy:provider/);
  assert.match(appJs, /Enable SnailLift in Extensions/);
  assert.match(css, /\.shell-trust-ribbon/);
  assert.match(css, /font-size:\s*clamp\(1\.55rem,\s*4vw,\s*2\.45rem\)/);
  assert.match(appJs, /@name@forest\.postsnail\.org/);
  assert.match(appJs, /data-settings-field="shellNameForestUrl"/);
  assert.match(appJs, /data-settings-field="shellNameDesiredName"/);
  assert.match(appJs, /data-settings-field="publicFont"/);
  assert.match(appJs, /data-settings-field="publicTextColor"/);
  assert.match(appJs, /PUBLIC_FONT_OPTIONS/);
  assert.match(appJs, /normalizePublicTextColor/);
  assert.match(appJs, /Preview: The quiet microblog stays readable/);
  assert.match(appJs, /data-action="register-shellname"/);
  assert.match(appJs, /data-action="update-shellname"/);
  assert.match(appJs, /data-action="renew-shellname"/);
  assert.match(appJs, /data-action="copy-shellname"/);
  assert.match(appJs, /not an account, DNS, or legal identity/);
  assert.match(appJs, /Open Shell/);
  assert.match(appJs, /Import Legacy Backup JSON/);
  assert.match(appJs, /Export Website ZIP/);
  assert.match(appJs, /Private source/);
  assert.match(appJs, /Public output/);
  assert.match(appJs, /After upload/);
  assert.match(appJs, /Shell saved/);
  assert.match(appJs, /Blog named/);
  assert.match(appJs, /One published post or page/);
  assert.match(appJs, /Show Powered by PostSnail/);
  assert.match(appJs, /Show tracker credit/);
  assert.match(appJs, /Notify Forest/);
  assert.match(appJs, /SnailLift/);
  assert.match(appJs, /Your shell stays private\. Your trail goes live\./);
  assert.match(appJs, /Surge setup/);
  assert.match(appJs, /Publish to Surge/);
  assert.match(appJs, /data-action="publish-snaillift-surge"/);
  assert.match(appJs, /data-settings-field="snailLiftSurgeSiteUrl"/);
  assert.match(appJs, /data-settings-field="snailLiftSurgeDomain"/);
  assert.match(appJs, /data-settings-field="snailLiftSurgeProjectDir"/);
  assert.match(appJs, /data-settings-field="snailLiftSurgeLogin"/);
  assert.match(appJs, /data-settings-field="snailLiftSurgeToken"/);
  assert.match(appJs, /Bridge helper/);
  assert.match(appJs, /Copy bridge command/);
  assert.match(appJs, /npm run surge:bridge/);
  assert.match(appJs, /Connected/);
  assert.match(appJs, /Publishing/);
  assert.match(appJs, /Deployment log/);
  assert.match(appJs, /renderSnailLiftLog/);
  assert.match(appJs, /<details class="deploy-log-item"/);
  assert.match(appJs, /formatDateTime\(log\.finishedAt \|\| log\.startedAt\)/);
  assert.match(appJs, /Started:/);
  assert.match(appJs, /Finished:/);
  assert.match(appJs, /data-action="verify-snaillift-live"/);
  assert.match(appJs, /data-action="announce-snaillift-forest"/);
  assert.match(appJs, /Change Domain/);
  assert.match(appJs, /data-action="submit-site-move"/);
  assert.match(appJs, /data-settings-field="siteMoveFromUrl"/);
  assert.match(appJs, /data-settings-field="siteMoveToUrl"/);
  assert.match(appJs, /ShellName alias/);
  assert.match(appJs, /buildSiteMovePayload/);
  assert.match(appJs, /buildMovedShellNameUpdate/);
  assert.match(appJs, /siteMoveSubmitting/);
  assert.match(appJs, /siteMoveErrorMessage/);
  assert.match(appJs, /Forest is rate limiting domain moves right now/);
  assert.doesNotMatch(submitSiteMoveSource, /state\.lastExportResult/);
  assert.doesNotMatch(submitSiteMoveSource, /Export Website ZIP first/);
  assert.match(submitSiteMoveSource, /expectedPublicKey:\s*state\.identity\.publicKey/);
  assert.match(submitSiteMoveSource, /bundleFingerprint:\s*liveVerification\.bundleFingerprint/);
  assert.match(submitSiteMoveSource, /\/shellnames\/update/);
  assert.doesNotMatch(submitSiteMoveSource, /buildCurrentWebsiteExport\(/);
  assert.match(appJs, /Forest notify unlocks only after live verification passes/);
  assert.match(appJs, /Upload ZIP contents to your live host/);
  assert.match(appJs, /Forest is waiting for your live site to show the new fingerprint/);
  assert.match(appJs, /https:\/\/forest\.postsnail\.org\/api\/announce/);
  assert.match(appJs, /\.postsnail/);
  assert.match(appJs, /\.zip/);
  assert.match(appJs, legalFooterPattern);
  assert.doesNotMatch(appJs, /hilazon6-logo\.png/);
  assert.doesNotMatch(appJs, /src="\.\/btc-wallet-qr\.svg"/);
  assert.doesNotMatch(appJs, /Export backup/);
  assert.doesNotMatch(appJs, /Import backup/);
  assert.doesNotMatch(appJs, /Export Workspace/);
  assert.doesNotMatch(appJs, /Import Workspace/);
  assert.doesNotMatch(appJs, /Open Local Shell/);
  assert.doesNotMatch(appJs, /aria-label="Hilazon6 home"/);

  assert.match(css, /--page:\s*#fffdf7/);
  assert.match(css, /--brand:\s*#ef4056/);
  assert.match(css, /--brand-ink:\s*#cf1e3d/);
  assert.match(css, /--line:\s*#16163c/);
  assert.match(css, /\[hidden\]\s*\{[\s\S]*display:\s*none\s*!important/);
  assert.match(css, /\.app-footer/);
  assert.match(css, /image-rendering:\s*pixelated/);
  assert.match(css, /\.shell-trust-ribbon/);
  assert.match(css, /\.shell-trust-item/);
  assert.match(css, /\.status-rail/);
  assert.match(css, /\.launch-guide/);
  assert.match(css, /\.writer-workbench/);
  assert.match(css, /\.writer-body/);
  assert.match(css, /\.writer-sidebar\s*\{[\s\S]*align-self:\s*start/);
  assert.match(css, /\.writer-sidebar\s*\{[\s\S]*position:\s*sticky/);
  assert.match(css, /\.writer-sidebar\s*\{[\s\S]*overflow:\s*auto/);
  assert.doesNotMatch(css, /\.writer-sidebar\s*\{[\s\S]*align-self:\s*stretch/);
  assert.match(css, /\.tab-menu\.open \.tab-submenu/);
  assert.doesNotMatch(css, /\.tab-menu\.active \.tab-submenu/);
  assert.match(css, /\.markdown-editor-mount \.cm-editor/);
  assert.match(css, /\.markdown-editor-mount \.ps-md-heading-line/);
  assert.match(css, /\.markdown-editor-mount \.ps-md-quote-line/);
  assert.match(css, /\.markdown-editor-mount \.ps-md-list-line/);
  assert.match(css, /\.markdown-editor-mount \.ps-md-code-token/);
  assert.match(css, /\.markdown-editor-mount \.ps-md-link-token/);
  assert.match(css, /\.field > span/);
  assert.doesNotMatch(css, /\.field span,/);
  assert.match(css, /\.font-preview/);
  assert.doesNotMatch(css, /\.markdown-source-editor/);
  assert.doesNotMatch(css, /\.markdown-editor-shell/);
  assert.doesNotMatch(css, /\.markdown-style-layer/);
  assert.doesNotMatch(css, /\.markdown-body-input/);
  assert.match(css, /\.image-grid/);
  assert.match(css, /repeat\(2, minmax\(0, 1fr\)\)/);
  assert.match(css, /\.image-preview-dialog/);
  assert.match(css, /\.image-preview-full/);
  assert.match(css, /\.image-insert-backdrop/);
  assert.match(css, /\.image-insert-dialog/);
  assert.match(css, /\.image-insert-grid/);
  assert.match(css, /\.image-insert-gallery-grid/);
  assert.match(css, /\.image-gallery-choice/);
  assert.match(css, /\.reading-preview-backdrop/);
  assert.match(css, /\.reading-preview-dialog/);
  assert.match(css, /\.reading-preview-page/);
  assert.match(css, /\.reading-preview-body/);
  assert.match(css, /\.launch-checklist/);
  assert.match(css, /\.admin-section-tabs/);
  assert.match(css, /\.generate-admin/);
  assert.match(css, /\.generate-hero/);
  assert.match(css, /\.generate-section-panel/);
  assert.match(css, /\.unlock-prompt/);
  assert.match(css, /\.site-move-checklist/);
  assert.match(css, /\.shell-gate\s*\{[\s\S]*gap:\s*10px/);
  assert.match(css, /\.shell-intro h1\s*\{[\s\S]*clamp\(1\.55rem,\s*4vw,\s*2\.45rem\)/);
  assert.match(css, /\.shell-card-grid/);
  assert.match(css, /\.create-shell-card/);
  assert.match(css, /\.recovery-shell-card/);
  assert.match(css, /\.pages-admin/);
  assert.match(css, /\.pages-list/);
  assert.match(css, /\.pages-editor/);
  assert.match(css, /\.comments-admin/);
  assert.match(css, /\.comments-workbench/);
  assert.match(css, /\.comment-row/);
  assert.match(css, /\.notify-forest-attention/);
  assert.match(css, /\.snaillift-panel/);
  assert.match(css, /\.deploy-command/);
  assert.match(css, /\.deploy-commands/);
  assert.match(css, /\.deploy-log/);
  assert.match(css, /\.deploy-log\s*\{[\s\S]*max-height:\s*min\(360px,\s*45dvh\);/);
  assert.match(css, /\.deploy-log-scroll/);
  assert.match(css, /\.deploy-log-scroll\s*\{[\s\S]*overflow:\s*auto;/);
  assert.match(css, /\.deploy-log-item/);
  assert.match(css, /\.deploy-log-summary/);
  assert.match(css, /\.deploy-log-body/);
  assert.match(css, /\.shellname-panel/);
  assert.match(css, /\.site-move-panel/);
  assert.match(css, /\.site-move-modes/);
  assert.match(css, /\.shellname-record/);
  assert.match(css, /animation:\s*notifyForestBlink[\s\S]*\s5;/);
  assert.match(css, /@media \(prefers-reduced-motion:\s*reduce\)[\s\S]*\.notify-forest-attention/);

  assert.match(headers, /connect-src 'self' https:/);
  assert.match(headers, /connect-src 'self' https:[^;]*https:\/\/forest\.postsnail\.org/);
  assert.match(headers, /www\.googletagmanager\.com/);
  assert.match(headers, /www\.google-analytics\.com/);
  assert.match(headers, /sha256-sIRPHA7SVkYAlsAr9nOEpJyk\+8KD8g8igOpfemf0u0o=/);
  assert.match(headers, /\/verify-remote\.html[\s\S]*www\.googletagmanager\.com/);
});

test("remote verifier generated page has matching public CSS support", () => {
  const html = read("verify-remote.html");
  const js = read("verify-remote.js");
  const css = read("site.css");

  assert.match(html, /src="\/verify-remote\.js"/);
  for (const className of ["notice", "check-list", "check-row", "hash-cell"]) {
    assert.match(js, new RegExp(className));
    assert.match(css, new RegExp(`\\.${className}`));
  }
  assert.match(css, /\.notice\.good/);
  assert.match(css, /\.notice\.warning/);
});

test("alpha public pages and documentation are present", () => {
  const pages = [
    ["manifesto/index.html", /PostSnail Manifesto/],
    ["media-kit/index.html", /PostSnail Media Kit/],
    ["docs/index.html", /PostSnail Documentation/],
    ["docs/how-to-use/index.html", /How To Use PostSnail/],
    ["docs/cli/index.html", /PostSnail CLI/],
    ["docs/headless-publishing/index.html", /Headless Publishing/],
    ["docs/publish-surge/index.html", /Publish On Surge/],
    ["docs/publishing/index.html", /Publishing PostSnail/],
    ["docs/snaillift/index.html", /SnailLift/],
    ["docs/snaillift-surge/index.html", /SnailLift Surge/],
    [
      "docs/snaillift-security/index.html",
      /Surge credentials are stored only in the encrypted Shell/,
    ],
    ["docs/comments/index.html", /PostSnail Comments/],
    ["docs/shellnames/index.html", /ShellNames/],
    ["docs/shellnames-protocol/index.html", /postsnail-shellname/],
    ["docs/shellnames-security/index.html", /not authority/],
    ["docs/site-moves/index.html", /Site Moves/],
    ["docs/concept/index.html", /PostSnail Concept/],
    ["docs/architecture/index.html", /PostSnail Architecture/],
    ["docs/core-foundation/index.html", /Core Foundation/],
    ["docs/plugin-system/index.html", /Plugin System/],
    ["docs/plugin-migrations/index.html", /Plugin Migrations/],
    ["docs/theme-system/index.html", /Theme System/],
    ["docs/theme-manifests/index.html", /Theme Manifests/],
    ["docs/route-assets/index.html", /Route Assets/],
    ["docs/permissions/index.html", /Permission Model/],
    ["docs/extension-security/index.html", /Extension Security/],
    ["docs/compatibility/index.html", /Compatibility Contract/],
    ["docs/protocol/index.html", /Protocol Reference/],
    ["docs/legal/index.html", /PostSnail Legal/],
    ["docs/workspace-vault/index.html", /Workspace Vault/],
    ["docs/migrations/index.html", /versioned workspace migrations/],
    ["docs/psep/index.html", /PostSnail Enhancement Proposals/],
    ["docs/security/index.html", /passphrase/],
  ];

  for (const [path, expected] of pages) {
    assert.match(read(path), expected, path);
  }

  assert.match(read("docs/index.html"), /Encrypted Workspace/);
  assert.match(read("docs/index.html"), /PostSnail CLI/);
  assert.match(read("docs/index.html"), /Headless Publishing/);
  assert.match(read("docs/index.html"), /SnailLift/);
  assert.match(read("docs/index.html"), /ShellNames/);
  assert.match(read("docs/publishing/index.html"), /Download ZIP remains the fallback/);
  assert.match(read("docs/snaillift/index.html"), /deployment assistant/);
  assert.match(read("docs/snaillift-surge/index.html"), /local Surge bridge/);
  assert.match(read("docs/snaillift-security/index.html"), /Forest notify is gated/);
  assert.match(read("docs/workspace-vault/index.html"), /\.postsnail/);
  assert.match(read("docs/workspace-vault/index.html"), /public Website ZIP/);
  assert.match(read("docs/compatibility/index.html"), /Unknown required features fail/);
  assert.match(read("docs/core-foundation/index.html"), /what PostSnail Core owns/);
  assert.match(read("docs/plugin-system/index.html"), /route-scoped runtime declarations/);
  assert.match(read("docs/plugin-migrations/index.html"), /missing plugin state is preserved/);
  assert.match(read("docs/theme-system/index.html"), /Admin themes/);
  assert.match(read("docs/theme-manifests/index.html"), /quiet-feed/);
  assert.match(read("docs/route-assets/index.html"), /declared per route/);
  assert.match(read("docs/permissions/index.html"), /Plugin permissions/);
  assert.match(read("docs/extension-security/index.html"), /Install does not mean load/);
  assert.match(read("docs/protocol/index.html"), /requiredFeatures/);
  assert.match(read("docs/psep/index.html"), /PSEP-0001/);
  assert.ok(existsSync(join(root, "docs/compatibility.md")));
  assert.ok(existsSync(join(root, "docs/protocol.md")));
  assert.ok(existsSync(join(root, "docs/publishing.md")));
  assert.ok(existsSync(join(root, "docs/snaillift.md")));
  assert.ok(existsSync(join(root, "docs/publish-surge.md")));
  assert.ok(existsSync(join(root, "docs/snaillift-surge.md")));
  assert.ok(existsSync(join(root, "docs/snaillift-security.md")));
  assert.ok(existsSync(join(root, "docs/core-foundation.md")));
  assert.ok(existsSync(join(root, "docs/plugin-system.md")));
  assert.ok(existsSync(join(root, "docs/plugin-migrations.md")));
  assert.ok(existsSync(join(root, "docs/theme-system.md")));
  assert.ok(existsSync(join(root, "docs/theme-manifests.md")));
  assert.ok(existsSync(join(root, "docs/route-assets.md")));
  assert.ok(existsSync(join(root, "docs/permissions.md")));
  assert.ok(existsSync(join(root, "docs/extension-security.md")));
  assert.ok(existsSync(join(root, "docs/roadmap/postsnail-master-roadmap-for-codex.md")));
  assert.ok(existsSync(join(root, "docs/roadmap/postsnail-core-foundation-plan.md")));
  assert.ok(existsSync(join(root, "docs/psep.md")));
  assert.ok(existsSync(join(root, "docs/pseps/PSEP-template.md")));
  assert.ok(existsSync(join(root, "docs/pseps/PSEP-0001-protocol-compatibility.md")));
  assert.ok(existsSync(join(root, "docs/workspace-vault.md")));
  assert.ok(existsSync(join(root, "docs/migrations.md")));
  assert.ok(existsSync(join(root, "docs/security.md")));
  assert.ok(existsSync(join(root, "docs/cli.md")));
  assert.ok(existsSync(join(root, "docs/headless-publishing.md")));
});

test("brand assets and reusable branding skills are committed", () => {
  assert.ok(existsSync(join(root, "assets/brand/postsnail-logo.webp")));
  assert.ok(existsSync(join(root, "assets/brand/postsnail-logo.png")));
  assert.ok(existsSync(join(root, "assets/brand/postsnail-icon.svg")));
  assert.ok(existsSync(join(root, "assets/brand/postsnail-icon.png")));

  const repoSkill = read("skills/postsnail-branding/SKILL.md");
  const globalSkill = readFileSync(
    "/Users/boazalhadeff/.codex/skills/postsnail-branding/SKILL.md",
    "utf8",
  );

  for (const skill of [repoSkill, globalSkill]) {
    assert.match(skill, /name: postsnail-branding/);
    assert.match(skill, /pixel-art/);
    assert.match(skill, /deep navy/);
    assert.match(skill, /coral/);
  }
});

test("transparent PNG brand assets are alpha-enabled", () => {
  assert.equal(pngColorType("assets/brand/postsnail-logo.png"), 6);
  assert.equal(pngColorType("assets/brand/postsnail-icon.png"), 6);
  assert.equal(pngColorType("favicon.png"), 6);
});

test("license, attribution notice, and third-party notices are present", () => {
  const rootPackage = JSON.parse(read("package.json"));
  const registryPackage = JSON.parse(read("registry/package.json"));
  const license = read("LICENSE");
  const notice = read("NOTICE");
  const thirdParty = read("THIRD_PARTY_NOTICES.md");
  const readme = read("README.md");

  assert.equal(rootPackage.license, "Apache-2.0");
  assert.equal(registryPackage.license, "Apache-2.0");
  assert.match(license, /Apache License/);
  assert.match(license, /Version 2\.0, January 2004/);
  assert.match(notice, /Boaz Alhadeff/);
  assert.match(notice, /PostSnail/);
  for (const name of ["@noble/post-quantum", "@noble/hashes", "fflate", "marked", "dompurify", "CodeMirror", "Lezer"]) {
    assert.match(thirdParty, new RegExp(name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  }
  assert.ok(existsSync(join(root, "vendor/postsnail-editor/LICENSES.md")));
  assert.match(readme, /Apache-2\.0/);
  assert.match(readme, /NOTICE/);
});

test("asset preparation publishes the public site and admin route", () => {
  execFileSync(process.execPath, ["scripts/prepare-admin-assets.js"], {
    cwd: root,
    stdio: "pipe",
  });

  const outDir = join(root, "dist/postsnail-admin");
  assert.ok(existsSync(join(outDir, "index.html")));
  assert.ok(existsSync(join(outDir, "LICENSE")));
  assert.ok(existsSync(join(outDir, "NOTICE")));
  assert.ok(existsSync(join(outDir, "THIRD_PARTY_NOTICES.md")));
  assert.ok(existsSync(join(outDir, "admin/index.html")));
  assert.ok(existsSync(join(outDir, "manifesto/index.html")));
  assert.ok(existsSync(join(outDir, "media-kit/index.html")));
  assert.ok(existsSync(join(outDir, "docs/architecture/index.html")));
  assert.ok(existsSync(join(outDir, "docs/cli/index.html")));
  assert.ok(existsSync(join(outDir, "docs/headless-publishing/index.html")));
  assert.ok(existsSync(join(outDir, "docs/publish-surge/index.html")));
  assert.ok(existsSync(join(outDir, "docs/publishing/index.html")));
  assert.ok(existsSync(join(outDir, "docs/snaillift/index.html")));
  assert.ok(existsSync(join(outDir, "docs/snaillift-surge/index.html")));
  assert.ok(existsSync(join(outDir, "docs/snaillift-security/index.html")));
  assert.ok(existsSync(join(outDir, "docs/core-foundation/index.html")));
  assert.ok(existsSync(join(outDir, "docs/plugin-system/index.html")));
  assert.ok(existsSync(join(outDir, "docs/plugin-migrations/index.html")));
  assert.ok(existsSync(join(outDir, "docs/theme-system/index.html")));
  assert.ok(existsSync(join(outDir, "docs/theme-manifests/index.html")));
  assert.ok(existsSync(join(outDir, "docs/route-assets/index.html")));
  assert.ok(existsSync(join(outDir, "docs/permissions/index.html")));
  assert.ok(existsSync(join(outDir, "docs/extension-security/index.html")));
  assert.ok(existsSync(join(outDir, "docs/compatibility/index.html")));
  assert.ok(existsSync(join(outDir, "docs/protocol/index.html")));
  assert.ok(existsSync(join(outDir, "docs/legal/index.html")));
  assert.ok(existsSync(join(outDir, "docs/workspace-vault/index.html")));
  assert.ok(existsSync(join(outDir, "docs/migrations/index.html")));
  assert.ok(existsSync(join(outDir, "docs/psep/index.html")));
  assert.ok(existsSync(join(outDir, "docs/security/index.html")));
  assert.ok(existsSync(join(outDir, "docs/compatibility.md")));
  assert.ok(existsSync(join(outDir, "docs/protocol.md")));
  assert.ok(existsSync(join(outDir, "docs/publishing.md")));
  assert.ok(existsSync(join(outDir, "docs/snaillift.md")));
  assert.ok(existsSync(join(outDir, "docs/publish-surge.md")));
  assert.ok(existsSync(join(outDir, "docs/snaillift-surge.md")));
  assert.ok(existsSync(join(outDir, "docs/snaillift-security.md")));
  assert.ok(existsSync(join(outDir, "docs/core-foundation.md")));
  assert.ok(existsSync(join(outDir, "docs/plugin-system.md")));
  assert.ok(existsSync(join(outDir, "docs/plugin-migrations.md")));
  assert.ok(existsSync(join(outDir, "docs/theme-system.md")));
  assert.ok(existsSync(join(outDir, "docs/theme-manifests.md")));
  assert.ok(existsSync(join(outDir, "docs/route-assets.md")));
  assert.ok(existsSync(join(outDir, "docs/permissions.md")));
  assert.ok(existsSync(join(outDir, "docs/extension-security.md")));
  assert.ok(existsSync(join(outDir, "docs/roadmap/postsnail-master-roadmap-for-codex.md")));
  assert.ok(existsSync(join(outDir, "docs/roadmap/postsnail-core-foundation-plan.md")));
  assert.ok(existsSync(join(outDir, "docs/psep.md")));
  assert.ok(existsSync(join(outDir, "docs/pseps/PSEP-template.md")));
  assert.ok(existsSync(join(outDir, "docs/pseps/PSEP-0001-protocol-compatibility.md")));
  assert.ok(existsSync(join(outDir, "docs/workspace-vault.md")));
  assert.ok(existsSync(join(outDir, "docs/migrations.md")));
  assert.ok(existsSync(join(outDir, "docs/security.md")));
  assert.ok(existsSync(join(outDir, "verify-remote.html")));
  assert.ok(existsSync(join(outDir, "assets/brand/postsnail-logo.webp")));
  assert.ok(existsSync(join(outDir, "assets/brand/postsnail-logo.png")));
  assert.ok(existsSync(join(outDir, "assets/brand/postsnail-icon.svg")));
  assert.deepEqual(findPreparedAssets(".DS_Store", outDir), []);

  for (const path of projectHtmlPages) {
    assert.match(readFileSync(join(outDir, path), "utf8"), legalFooterPattern, path);
  }
});

function findPreparedAssets(name, directory, found = []) {
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.name === name) found.push(path);
    if (entry.isDirectory()) findPreparedAssets(name, path, found);
  }
  return found;
}

function pngColorType(path) {
  const bytes = readFileSync(join(root, path));
  assert.equal(bytes.toString("ascii", 1, 4), "PNG", path);
  return bytes[25];
}
