import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { test } from "node:test";

const root = process.cwd();
const legalFooterPattern = /© 2026 Boaz Alhadeff[\s\S]*Apache-2\.0[\s\S]*NOTICE/;
const generatedMarker = /Generated by scripts\/generate-public-site\.js/;
const projectHtmlPages = [
  "index.html",
  "features-qa.html",
  "verify-remote.html",
  "manifesto/index.html",
  "media-kit/index.html",
  "docs/index.html",
  "docs/how-to-use/index.html",
  "docs/publish-cloudflare/index.html",
  "docs/concept/index.html",
  "docs/architecture/index.html",
  "docs/compatibility/index.html",
  "docs/protocol/index.html",
  "docs/workspace-vault/index.html",
  "docs/security/index.html",
  "docs/migrations/index.html",
  "docs/psep/index.html",
  "docs/legal/index.html",
];

function read(path) {
  return readFileSync(join(root, path), "utf8");
}

test("public landing page is separate from the browser admin", () => {
  const html = read("index.html");

  assert.match(html, /PostSnail Alpha 1/);
  assert.match(html, /id="landing-search"/);
  assert.match(html, /data-forest-url="https:\/\/forest\.postsnail\.org\/"/);
  assert.doesNotMatch(html, /id="app" class="app-shell"/);
  assert.doesNotMatch(html, /src="\.\/app\.js"/);
});

test("admin shell is reachable from /admin/", () => {
  const html = read("admin/index.html");

  assert.match(html, /PostSnail - Static Microblog Admin/);
  assert.match(html, /<main id="app" class="app-shell"/);
  assert.match(html, /href="\.\.\/styles\.css"/);
  assert.match(html, /src="\.\.\/app\.js"/);
  assert.match(html, legalFooterPattern);
});

test("public pages are generated from the shared PostSnail layout", () => {
  assert.ok(existsSync(join(root, "scripts/generate-public-site.js")));
  execFileSync(process.execPath, ["scripts/generate-public-site.js"], {
    cwd: root,
    stdio: "pipe",
  });

  for (const path of projectHtmlPages) {
    const html = read(path);
    assert.match(html, generatedMarker, path);
    assert.match(html, /class="site-footer"/, path);
    assert.match(html, legalFooterPattern, path);
    assert.match(html, /href="\/docs\/legal\/"/, path);
    assert.match(html, /href="\/LICENSE"/, path);
    assert.match(html, /href="\/NOTICE"/, path);
    assert.match(html, /href="\/THIRD_PARTY_NOTICES\.md"/, path);
  }
});

test("admin app uses the PostSnail brand skin and compact legal footer", () => {
  const appJs = read("app.js");
  const css = read("styles.css");
  const headers = read("_headers");

  assert.match(appJs, /renderShellGate/);
  assert.match(appJs, /Open Shell/);
  assert.match(appJs, /Create Shell/);
  assert.match(appJs, /open-shell-card/);
  assert.match(appJs, /create-shell-card/);
  assert.match(appJs, /recovery-shell-card/);
  assert.match(appJs, /Start a new private Shell/);
  assert.match(appJs, /This creates a signature workspace, not an account/);
  assert.match(appJs, /shell-create-title/);
  assert.match(appJs, /shell-create-passphrase/);
  assert.match(appJs, /shell-create-confirm/);
  assert.match(appJs, /Unlock Local Shell/);
  assert.match(appJs, /Migrate Local Data/);
  assert.match(appJs, /Close Shell/);
  assert.match(appJs, /Old browser-local data is not locked yet/);
  assert.match(appJs, /A Shell is your private PostSnail workspace/);
  assert.match(appJs, /Your identity is a signature key, not a profile login/);
  assert.match(appJs, /No account\. No email\. No backend login\./);
  assert.match(appJs, /Your Shell stays private\. Your Website ZIP is public\./);
  assert.match(appJs, /renderAppFooter/);
  assert.match(appJs, /postsnail-icon\.png/);
  assert.match(appJs, /src="\.\.\/btc-wallet-qr\.svg"/);
  assert.match(appJs, /Export Shell/);
  assert.match(appJs, /Open Shell/);
  assert.match(appJs, /Import Legacy Backup JSON/);
  assert.match(appJs, /Export Website ZIP/);
  assert.match(appJs, /Show Powered by PostSnail/);
  assert.match(appJs, /Show tracker credit/);
  assert.match(appJs, /Notify Forest/);
  assert.match(appJs, /Upload ZIP contents to your live host/);
  assert.match(appJs, /Forest is waiting for your live site to show the new fingerprint/);
  assert.match(appJs, /https:\/\/forest\.postsnail\.org\/api\/announce/);
  assert.match(appJs, /\.postsnail/);
  assert.match(appJs, /\.zip/);
  assert.match(appJs, legalFooterPattern);
  assert.doesNotMatch(appJs, /hilazon6-logo\.png/);
  assert.doesNotMatch(appJs, /src="\.\/btc-wallet-qr\.svg"/);
  assert.doesNotMatch(appJs, /Export backup/);
  assert.doesNotMatch(appJs, /Import backup/);
  assert.doesNotMatch(appJs, /Export Workspace/);
  assert.doesNotMatch(appJs, /Import Workspace/);
  assert.doesNotMatch(appJs, /Open Local Shell/);
  assert.doesNotMatch(appJs, /aria-label="Hilazon6 home"/);

  assert.match(css, /--page:\s*#fffdf7/);
  assert.match(css, /--brand:\s*#ef4056/);
  assert.match(css, /--brand-ink:\s*#cf1e3d/);
  assert.match(css, /--line:\s*#16163c/);
  assert.match(css, /\.app-footer/);
  assert.match(css, /image-rendering:\s*pixelated/);
  assert.match(css, /\.shell-card-grid/);
  assert.match(css, /\.create-shell-card/);
  assert.match(css, /\.recovery-shell-card/);
  assert.match(css, /\.notify-forest-attention/);
  assert.match(css, /animation:\s*notifyForestBlink[\s\S]*\s5;/);
  assert.match(css, /@media \(prefers-reduced-motion:\s*reduce\)[\s\S]*\.notify-forest-attention/);

  assert.match(headers, /connect-src 'self' https:\/\/forest\.postsnail\.org/);
});

test("remote verifier generated page has matching public CSS support", () => {
  const html = read("verify-remote.html");
  const js = read("verify-remote.js");
  const css = read("site.css");

  assert.match(html, /src="\/verify-remote\.js"/);
  for (const className of ["notice", "check-list", "check-row", "hash-cell"]) {
    assert.match(js, new RegExp(className));
    assert.match(css, new RegExp(`\\.${className}`));
  }
  assert.match(css, /\.notice\.good/);
  assert.match(css, /\.notice\.warning/);
});

test("alpha public pages and documentation are present", () => {
  const pages = [
    ["manifesto/index.html", /PostSnail Manifesto/],
    ["media-kit/index.html", /PostSnail Media Kit/],
    ["docs/index.html", /PostSnail Documentation/],
    ["docs/how-to-use/index.html", /How To Use PostSnail/],
    ["docs/publish-cloudflare/index.html", /Publish On Cloudflare Pages/],
    ["docs/concept/index.html", /PostSnail Concept/],
    ["docs/architecture/index.html", /PostSnail Architecture/],
    ["docs/compatibility/index.html", /Compatibility Contract/],
    ["docs/protocol/index.html", /Protocol Reference/],
    ["docs/legal/index.html", /PostSnail Legal/],
    ["docs/workspace-vault/index.html", /Workspace Vault/],
    ["docs/migrations/index.html", /versioned workspace migrations/],
    ["docs/psep/index.html", /PostSnail Enhancement Proposals/],
    ["docs/security/index.html", /passphrase/],
  ];

  for (const [path, expected] of pages) {
    assert.match(read(path), expected, path);
  }

  assert.match(read("docs/index.html"), /Encrypted Workspace/);
  assert.match(read("docs/workspace-vault/index.html"), /\.postsnail/);
  assert.match(read("docs/workspace-vault/index.html"), /public Website ZIP/);
  assert.match(read("docs/compatibility/index.html"), /Unknown required features fail/);
  assert.match(read("docs/protocol/index.html"), /requiredFeatures/);
  assert.match(read("docs/psep/index.html"), /PSEP-0001/);
  assert.ok(existsSync(join(root, "docs/compatibility.md")));
  assert.ok(existsSync(join(root, "docs/protocol.md")));
  assert.ok(existsSync(join(root, "docs/psep.md")));
  assert.ok(existsSync(join(root, "docs/pseps/PSEP-template.md")));
  assert.ok(existsSync(join(root, "docs/pseps/PSEP-0001-protocol-compatibility.md")));
  assert.ok(existsSync(join(root, "docs/workspace-vault.md")));
  assert.ok(existsSync(join(root, "docs/migrations.md")));
  assert.ok(existsSync(join(root, "docs/security.md")));
});

test("brand assets and reusable branding skills are committed", () => {
  assert.ok(existsSync(join(root, "assets/brand/postsnail-logo.webp")));
  assert.ok(existsSync(join(root, "assets/brand/postsnail-logo.png")));
  assert.ok(existsSync(join(root, "assets/brand/postsnail-icon.svg")));
  assert.ok(existsSync(join(root, "assets/brand/postsnail-icon.png")));

  const repoSkill = read("skills/postsnail-branding/SKILL.md");
  const globalSkill = readFileSync(
    "/Users/boazalhadeff/.codex/skills/postsnail-branding/SKILL.md",
    "utf8",
  );

  for (const skill of [repoSkill, globalSkill]) {
    assert.match(skill, /name: postsnail-branding/);
    assert.match(skill, /pixel-art/);
    assert.match(skill, /deep navy/);
    assert.match(skill, /coral/);
  }
});

test("transparent PNG brand assets are alpha-enabled", () => {
  assert.equal(pngColorType("assets/brand/postsnail-logo.png"), 6);
  assert.equal(pngColorType("assets/brand/postsnail-icon.png"), 6);
  assert.equal(pngColorType("favicon.png"), 6);
});

test("license, attribution notice, and third-party notices are present", () => {
  const rootPackage = JSON.parse(read("package.json"));
  const registryPackage = JSON.parse(read("registry/package.json"));
  const license = read("LICENSE");
  const notice = read("NOTICE");
  const thirdParty = read("THIRD_PARTY_NOTICES.md");
  const readme = read("README.md");

  assert.equal(rootPackage.license, "Apache-2.0");
  assert.equal(registryPackage.license, "Apache-2.0");
  assert.match(license, /Apache License/);
  assert.match(license, /Version 2\.0, January 2004/);
  assert.match(notice, /Boaz Alhadeff/);
  assert.match(notice, /PostSnail/);
  for (const name of ["@noble/post-quantum", "@noble/hashes", "fflate", "marked", "dompurify"]) {
    assert.match(thirdParty, new RegExp(name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  }
  assert.match(readme, /Apache-2\.0/);
  assert.match(readme, /NOTICE/);
});

test("asset preparation publishes the public site and admin route", () => {
  execFileSync(process.execPath, ["scripts/prepare-admin-assets.js"], {
    cwd: root,
    stdio: "pipe",
  });

  const outDir = join(root, "dist/postsnail-admin");
  assert.ok(existsSync(join(outDir, "index.html")));
  assert.ok(existsSync(join(outDir, "LICENSE")));
  assert.ok(existsSync(join(outDir, "NOTICE")));
  assert.ok(existsSync(join(outDir, "THIRD_PARTY_NOTICES.md")));
  assert.ok(existsSync(join(outDir, "admin/index.html")));
  assert.ok(existsSync(join(outDir, "manifesto/index.html")));
  assert.ok(existsSync(join(outDir, "media-kit/index.html")));
  assert.ok(existsSync(join(outDir, "docs/architecture/index.html")));
  assert.ok(existsSync(join(outDir, "docs/compatibility/index.html")));
  assert.ok(existsSync(join(outDir, "docs/protocol/index.html")));
  assert.ok(existsSync(join(outDir, "docs/legal/index.html")));
  assert.ok(existsSync(join(outDir, "docs/workspace-vault/index.html")));
  assert.ok(existsSync(join(outDir, "docs/migrations/index.html")));
  assert.ok(existsSync(join(outDir, "docs/psep/index.html")));
  assert.ok(existsSync(join(outDir, "docs/security/index.html")));
  assert.ok(existsSync(join(outDir, "docs/compatibility.md")));
  assert.ok(existsSync(join(outDir, "docs/protocol.md")));
  assert.ok(existsSync(join(outDir, "docs/psep.md")));
  assert.ok(existsSync(join(outDir, "docs/pseps/PSEP-template.md")));
  assert.ok(existsSync(join(outDir, "docs/pseps/PSEP-0001-protocol-compatibility.md")));
  assert.ok(existsSync(join(outDir, "docs/workspace-vault.md")));
  assert.ok(existsSync(join(outDir, "docs/migrations.md")));
  assert.ok(existsSync(join(outDir, "docs/security.md")));
  assert.ok(existsSync(join(outDir, "verify-remote.html")));
  assert.ok(existsSync(join(outDir, "assets/brand/postsnail-logo.webp")));
  assert.ok(existsSync(join(outDir, "assets/brand/postsnail-logo.png")));
  assert.ok(existsSync(join(outDir, "assets/brand/postsnail-icon.svg")));

  for (const path of projectHtmlPages) {
    assert.match(readFileSync(join(outDir, path), "utf8"), legalFooterPattern, path);
  }
});

function pngColorType(path) {
  const bytes = readFileSync(join(root, path));
  assert.equal(bytes.toString("ascii", 1, 4), "PNG", path);
  return bytes[25];
}
